### PR TITLE
enable sanitization for tezos messages

### PR DESCRIPTION
**Pull request by mat13mn**
- New version for develop
- - run 'cargo check' once per OS - run 'cargo test' for every combination except macos with address sanitizer

### CODE REVIEW

**Review by bkontur — APPROVED** [review]

**Comment by bkontur** [comment]
@mat13mn 
rebase to develop and merge please

**Comment by tizoc** [comment]
@mat13mn this one was approved seems to have been forgotten. Btw, can you also include the simplification we discussed? (using either `include` or `exclude` in the matrix to avoid the need to filter macos+address with an `if`)

**Comment by bkontur** [comment]
@mat13mn @tizoc 
guys, what about this PR?

**Comment by mat13mn** [comment]
there is still one comment from bruno that i need to adress - haven't had time yet - will do that soon

**Comment by tizoc** [comment]
Closing this, will solve it as part of  #499 because I have to fix other things on the github actions file anyway because of the upgrade to ocaml-sys 0.20

**Pull request closed without merging**
