### PR TITLE
Multi backend merkle

### PR DESCRIPTION
**Pull request by mambisi**

### CODE REVIEW

**Comment by tizoc** [comment]
@mambisi are this PR and #388 still relevant? if no, why?

**Comment by mambisi** [comment]
No its not, its already merged with `fb_storage_extended_actions_backtracking_support`

**Comment by tizoc** [comment]
@mambisi I see, so, how was this merged? directly without going through Github? We should avoid doing that.

**Comment by tizoc** [comment]
Btw please close this and the other PRs that are not longer relevant.

**Pull request closed without merging**
