### PR TITLE
[TE-249] Remove panic from encode record

### PR DESCRIPTION
**Pull request by akoptelov**
Remove `panic!` with returning error result.

### CODE REVIEW

**Comment by akoptelov** [comment]
This PR is basing on #368.

**Comment by tizoc** [comment]
@akoptelov is this one ready for review? still marked as "draft"

**Comment by akoptelov** [comment]
It is ready now.

**Review by bkontur — APPROVED** [review]
@akoptelov 
please, rebase and merge to develop

**Pull request merged**
