### PR TITLE
Remove panic! and unwrap() from merkle_storage.rs

### PR DESCRIPTION
**Pull request by akoptelov**
- Properly handle `Option` values
- Introduce an error for missing expected value
- Introduce an error for unexpected state of the system

@bkontur 
There's a comment `//TODO: panic?`. Any suggestion here? Should we
return `Err(InvalidState)` instead?

### CODE REVIEW

**Review by bkontur — APPROVED** [review]
@mat13mn 
Mateusz, could you please check this PR also?

**Comment by mat13mn** [comment]
LGTM

**Comment by bkontur** [comment]
> LGTM

@akoptelov 
please, rebase and merge to develop

**Review by mat13mn — APPROVED** [review]
lgtm

**Comment by akoptelov** [comment]
There are some new `unwrap`s in the file. Need to remove them as well. Will affect some other files as well.

**Comment by tizoc** [comment]
@bkontur @akoptelov this file is going to be changing quite a bit soon, so probably not a priority compared to other places.

**Comment by akoptelov** [comment]
> @bkontur @akoptelov this file is going to be changing quite a bit soon, so probably not a priority compared to other places.

I've resolved the conflicts, @tizoc @mat13mn please take another look at it, if you're ok with that we can merge that way and remove the rest of unwraps later.

**Review by tizoc — APPROVED** [review]
Looks good👍

**Review by bkontur — APPROVED** [review]
@akoptelov 
please rebase and merge to develop

**Comment by akoptelov** [comment]
> @akoptelov
> please rebase and merge to develop

@bkontur This now intersects a lot with @mat13mn's PR. Probably it is better to hold this one off until #463 is merged.
@mat13mn FYI.

**Comment by akoptelov** [comment]
> > @akoptelov
> > please rebase and merge to develop
> 
> @bkontur This now intersects a lot with @mat13mn's PR. Probably it is better to hold this one off until #463 is merged.
> @mat13mn FYI.

Hmm... Actually not that lot. Anyway, @mat13mn will you be able to see that this PR won't cause too many troubles?

**Comment by akoptelov** [comment]
@mat13mn Rebasing your PR on top of this one will result about 4 conflicts, and tt should be pretty straightforward to resolve them. So I'm merging this one.

**Pull request merged**
